# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Copybirds < Formula
  desc "Capture runtime file dependencies of Linux programs"
  homepage "https://github.com/afeldman/copybirds"
  version "0.1.0"
  license "Apache-2.0"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/afeldman/copybirds/releases/download/v0.1.0/copybirds_0.1.0_linux_x86_64.tar.gz"
    sha256 "660c59b7e46414d154802ffa7f824730085f3e6c075a823f988c0cf52409d368"
    define_method(:install) do
      bin.install "cb"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/afeldman/copybirds/releases/download/v0.1.0/copybirds_0.1.0_linux_arm64.tar.gz"
    sha256 "19509af18c5f72fe4c9b77a1716a4557227ec18c5ff3e9eef08c50267189e4f1"
    define_method(:install) do
      bin.install "cb"
    end
  end
end
