# This file was generated by GoReleaser. DO NOT EDIT.
cask "batch-cost" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/afeldman/batch-cost/releases/download/v#{version}/batch-cost_#{version}_darwin_amd64.tar.gz"
      sha256 "70b0aba45da2a23cfef69b05ac9b09c88ca7a2ab7ea8234f216e6f11a6a1e29c"
    end
    on_arm do
      url "https://github.com/afeldman/batch-cost/releases/download/v#{version}/batch-cost_#{version}_darwin_arm64.tar.gz"
      sha256 "4618912590b66f6e63d07e75cb41c84b6b4a5b33549c5b1ac1a8a0edd29c5132"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/afeldman/batch-cost/releases/download/v#{version}/batch-cost_#{version}_linux_amd64.tar.gz"
      sha256 "dacd71e685f17259a66aac2f55f40f30ac3c6670e58c9c078a0f6cfe47a2ec72"
    end
    on_arm do
      url "https://github.com/afeldman/batch-cost/releases/download/v#{version}/batch-cost_#{version}_linux_arm64.tar.gz"
      sha256 "db652b6daedf01c33a1c4527b95a79fb028bf85d206d9b8b983c50e46c032921"
    end
  end

  name "batch-cost"
  desc "AWS Batch job cost estimator"
  homepage "https://github.com/afeldman/batch-cost"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "batch-cost"

  # No zap stanza required

end
