# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudlogin" do
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/afeldman/cloudlogin/releases/download/v#{version}/cloudlogin_#{version}_darwin_amd64.tar.gz"
      sha256 "02def42b3155778e029d0a576a0ac1a66bf2cb958ff9d117de1007b4d20b91bd"
    end
    on_arm do
      url "https://github.com/afeldman/cloudlogin/releases/download/v#{version}/cloudlogin_#{version}_darwin_arm64.tar.gz"
      sha256 "2ebf3c25f57030550a4d2658f9f761b74193ba4401858762b699721baf11a1a4"
    end
  end

  name "cloudlogin"
  desc "AWS + Kubernetes SSO Connection Manager"
  homepage "https://github.com/afeldman/cloudlogin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloudlogin"

  # No zap stanza required

end
