# This file was generated by GoReleaser. DO NOT EDIT.
cask "cpctl" do
  version "0.10.0"

  on_macos do
    on_intel do
      url "https://github.com/afeldman/cloud-playground/releases/download/v#{version}/cpctl_#{version}_darwin_amd64.tar.gz"
      sha256 "d5366a2d73c82611918075cdb95e821353259332edc9211dff13f82fc9a060d0"
    end
    on_arm do
      url "https://github.com/afeldman/cloud-playground/releases/download/v#{version}/cpctl_#{version}_darwin_arm64.tar.gz"
      sha256 "5f6ce108e63a935874382ec0fc7f66e1582e1fd1481017fc2ddf6de9db505bc2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/afeldman/cloud-playground/releases/download/v#{version}/cpctl_#{version}_linux_amd64.tar.gz"
      sha256 "0df110e26e99d1f5032ec3f43bc1090d9ae060e5d201d3e87a56ac05901b0f4a"
    end
    on_arm do
      url "https://github.com/afeldman/cloud-playground/releases/download/v#{version}/cpctl_#{version}_linux_arm64.tar.gz"
      sha256 "844acdf0667af829c9695675b4f39e76e82d31ff77c4f306be67e12cd36a1998"
    end
  end

  name "cpctl"
  desc "Cloud Playground: Local dev platform for AWS + Kubernetes"
  homepage "https://github.com/afeldman/cloud-playground"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cpctl"

  # No zap stanza required

end
