# This file was generated by GoReleaser. DO NOT EDIT.
cask "cpctl" do
  version "0.10.5"

  on_macos do
    on_intel do
      url "https://github.com/afeldman/cloud-playground/releases/download/v#{version}/cpctl_#{version}_darwin_amd64.tar.gz"
      sha256 "1e05ee96d47ad157bdbc5eda5d5917f736d12f5c44c9fde6dcf9815bbaa17e0a"
    end
    on_arm do
      url "https://github.com/afeldman/cloud-playground/releases/download/v#{version}/cpctl_#{version}_darwin_arm64.tar.gz"
      sha256 "525ac468fb2ac1f028dd9080f199aa378382bfa0d767f3ef1165279a7ada87ed"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/afeldman/cloud-playground/releases/download/v#{version}/cpctl_#{version}_linux_amd64.tar.gz"
      sha256 "af88f1f05d1d6e3d06a6db36a80974d13e54f781f9abcbce100e846b6568eb4a"
    end
    on_arm do
      url "https://github.com/afeldman/cloud-playground/releases/download/v#{version}/cpctl_#{version}_linux_arm64.tar.gz"
      sha256 "32ec87d38b64cb83886730673bf6a1e0ab58f291f40bda71dd0c3ed44bb18b91"
    end
  end

  name "cpctl"
  desc "Cloud Playground: Local dev platform for AWS + Kubernetes"
  homepage "https://github.com/afeldman/cloud-playground"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cpctl"

  # No zap stanza required

end
