# This file was generated by GoReleaser. DO NOT EDIT.
cask "cpctl" do
  version "0.10.6"

  on_macos do
    on_intel do
      url "https://github.com/afeldman/cloud-playground/releases/download/v#{version}/cpctl_#{version}_darwin_amd64.tar.gz"
      sha256 "c71421fcd3dbbf8aee095289ba6db9d71ea774cd5065a207026d6aafef578e43"
    end
    on_arm do
      url "https://github.com/afeldman/cloud-playground/releases/download/v#{version}/cpctl_#{version}_darwin_arm64.tar.gz"
      sha256 "dd6bc28d999481131e44cdd80ea893a95184d9430c1ce50e3369cd24be6ff0be"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/afeldman/cloud-playground/releases/download/v#{version}/cpctl_#{version}_linux_amd64.tar.gz"
      sha256 "e2861db8a5de3b751cd3db4c27fbcfd51bd71feae6aae7ccbe5682a05d7a891e"
    end
    on_arm do
      url "https://github.com/afeldman/cloud-playground/releases/download/v#{version}/cpctl_#{version}_linux_arm64.tar.gz"
      sha256 "53efc7ca1f567a75834a271594055adefd19bbdd26d979e13e59a1c087b59150"
    end
  end

  name "cpctl"
  desc "Cloud Playground: Local dev platform for AWS + Kubernetes"
  homepage "https://github.com/afeldman/cloud-playground"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cpctl"

  # No zap stanza required

end
