# This file was generated by GoReleaser. DO NOT EDIT.
cask "gofish" do
  version "0.16.10"

  on_macos do
    on_intel do
      url "https://github.com/afeldman/gofish/releases/download/v#{version}/gofish_#{version}_darwin_amd64.tar.gz"
      sha256 "547e4b9f5600d6cf9466575cb7d823f422cc34c68293ed2b4bc302014167833f"
    end
    on_arm do
      url "https://github.com/afeldman/gofish/releases/download/v#{version}/gofish_#{version}_darwin_arm64.tar.gz"
      sha256 "3c2285c147dff41cc3bf69150831e02dc099347ae945685dd3e3981ee0043f9f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/afeldman/gofish/releases/download/v#{version}/gofish_#{version}_linux_amd64.tar.gz"
      sha256 "96aae810460dac28f8dc18e116cd5077048e4f373e5cfe3ba0f7dfc757de6fc7"
    end
    on_arm do
      url "https://github.com/afeldman/gofish/releases/download/v#{version}/gofish_#{version}_linux_arm64.tar.gz"
      sha256 "369e262024f220a94212f104ab4dd19c5ec9f624814468175e56fa60916aa495"
    end
  end

  name "gofish"
  desc "Cross-platform package manager (GoFish fork)"
  homepage "https://github.com/afeldman/gofish"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gofish"

  # No zap stanza required

end
