# This file will be auto-generated by GoReleaser on release.
# DO NOT EDIT MANUALLY - it will be overwritten.
#
# For manual testing or documentation, you can use this template.
# Actual releases will generate the proper URLs and checksums.

cask "goshellcheck" do
  version "0.0.0"

  on_macos do
    on_intel do
      url "https://github.com/afeldman/goshellcheck/releases/download/v#{version}/goshellcheck_#{version}_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_FOR_DOCUMENTATION_ONLY"
    end
    on_arm do
      url "https://github.com/afeldman/goshellcheck/releases/download/v#{version}/goshellcheck_#{version}_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_FOR_DOCUMENTATION_ONLY"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/afeldman/goshellcheck/releases/download/v#{version}/goshellcheck_#{version}_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_FOR_DOCUMENTATION_ONLY"
    end
    on_arm do
      url "https://github.com/afeldman/goshellcheck/releases/download/v#{version}/goshellcheck_#{version}_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_FOR_DOCUMENTATION_ONLY"
    end
  end

  name "goshellcheck"
  desc "ShellCheck in Go - shell script static analysis tool"
  homepage "https://github.com/afeldman/goshellcheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goshellcheck"

  # No zap stanza required

end
