# This file was generated by GoReleaser. DO NOT EDIT.
cask "goshellcheck" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/afeldman/goshellcheck/releases/download/v#{version}/goshellcheck_#{version}_darwin_amd64.tar.gz"
      sha256 "1bc004e9d01dd0b4b39483b1e3e4cf60c16e26fa69cba603f965c4da75ea9534"
    end
    on_arm do
      url "https://github.com/afeldman/goshellcheck/releases/download/v#{version}/goshellcheck_#{version}_darwin_arm64.tar.gz"
      sha256 "8dc6967b0c656f7ed278a3671a680c488e7ee32971ad1d653a9aaa8af467c9ca"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/afeldman/goshellcheck/releases/download/v#{version}/goshellcheck_#{version}_linux_amd64.tar.gz"
      sha256 "2fbd48dab944d434a3c7debc329d436c7ba039ccbd6d776316f6c1cf3bd01661"
    end
    on_arm do
      url "https://github.com/afeldman/goshellcheck/releases/download/v#{version}/goshellcheck_#{version}_linux_arm64.tar.gz"
      sha256 "534f2cb3d765b51b5b7e8f593d09fda48b0a01994471094d1f987cd4bc0bebee"
    end
  end

  name "goshellcheck"
  desc "ShellCheck in Go"
  homepage "https://github.com/afeldman/goshellcheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goshellcheck"

  # No zap stanza required

end
