# This file was generated by GoReleaser. DO NOT EDIT.
cask "goshred" do
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/afeldman/shred/releases/download/v#{version}/shred_#{version}_darwin_amd64.tar.gz"
      sha256 "de42bbc39320ed087f00938ac4f5a4748dd84f5fcccc2541df3f77b78187da68"
    end
    on_arm do
      url "https://github.com/afeldman/shred/releases/download/v#{version}/shred_#{version}_darwin_arm64.tar.gz"
      sha256 "5a4fbaad41a5b24ec1601ad5fb54fba7a782c8c5faa9bfe681e8247beefc6db7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/afeldman/shred/releases/download/v#{version}/shred_#{version}_linux_amd64.tar.gz"
      sha256 "cbf0bbb5c5f09e90b35c78c8f017bbeb41a23c5a18c59470fe29e37398d267a3"
    end
    on_arm do
      url "https://github.com/afeldman/shred/releases/download/v#{version}/shred_#{version}_linux_arm64.tar.gz"
      sha256 "113e3e3a24848622936ae4b117b5261706d5a5955b7a5cdc7a128f95f425c350"
    end
  end

  name "goshred"
  desc "Secure file deletion (Gutmann, DoD, VSITR)"
  homepage "https://github.com/afeldman/shred"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goshred"

  # No zap stanza required

end
