# This file was generated by GoReleaser. DO NOT EDIT.
cask "project-check" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/afeldman/project-check/releases/download/v#{version}/project-check_#{version}_darwin_amd64.tar.gz"
      sha256 "651a55eb93e85968a24e8d36134a9f2ca36ff43eca56e234e8a119b43b2d5fdf"
    end
    on_arm do
      url "https://github.com/afeldman/project-check/releases/download/v#{version}/project-check_#{version}_darwin_arm64.tar.gz"
      sha256 "a565a82b2de4726e9d72c2c83d920de8a79764efc7d7bac42ed9299c67a40fa0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/afeldman/project-check/releases/download/v#{version}/project-check_#{version}_linux_amd64.tar.gz"
      sha256 "26259c1cabf90374f033713366b33959329b99dcdb8bcdbe7cff4ad80885246c"
    end
    on_arm do
      url "https://github.com/afeldman/project-check/releases/download/v#{version}/project-check_#{version}_linux_arm64.tar.gz"
      sha256 "3d7988c43b6968e0cbf127105032e52ae3de9fae48dfa28d5c2fa52095f56efa"
    end
  end

  name "project-check"
  desc "LLM-powered project standards checker"
  homepage "https://github.com/afeldman/project-check"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "project-check"

  # No zap stanza required

end
