# This file was generated by GoReleaser. DO NOT EDIT.
cask "shred" do
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/afeldman/shred/releases/download/v#{version}/shred_#{version}_darwin_amd64.tar.gz"
      sha256 "9d058f1ddfbac2150bc32e1fdb4da6845c7a7b738ce655c5718e71ea00d4393d"
    end
    on_arm do
      url "https://github.com/afeldman/shred/releases/download/v#{version}/shred_#{version}_darwin_arm64.tar.gz"
      sha256 "6d63c618e0f21372c1ccfcb2f2e82dbf7fd75d66df502c8b35925d611624dd7d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/afeldman/shred/releases/download/v#{version}/shred_#{version}_linux_amd64.tar.gz"
      sha256 "2e57610574025ae091dd67ece6adef2eaa50eb89840bf705eb02bb47bfddfd26"
    end
    on_arm do
      url "https://github.com/afeldman/shred/releases/download/v#{version}/shred_#{version}_linux_arm64.tar.gz"
      sha256 "99f48ac9c27bb7a4e559851d66a8d02862192fbdb8dfd0ae3e3de73781d2e2b3"
    end
  end

  name "shred"
  desc "Secure file deletion (Gutmann, DoD, VSITR)"
  homepage "https://github.com/afeldman/shred"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shred"

  # No zap stanza required

end
