# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kairos < Formula
  desc "Git Context Engine — understands project history to generate high-quality commit messages, tags, and changelogs using LLMs"
  homepage "https://github.com/afeldman/kairos"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/afeldman/kairos/releases/download/v0.3.0/kairos_0.3.0_macOS_arm64.tar.gz"
      sha256 "fbf43158f469fe062d170020f2c5a6e9f29f2b331c3be00831d86496ad787c33"

      define_method(:install) do
        bin.install "kairos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/afeldman/kairos/releases/download/v0.3.0/kairos_0.3.0_Linux_x86_64.tar.gz"
      sha256 "3a01358674b1326830bfab0fb50c24c782b702c88b73dce2ad5359fc40d9ffc6"
      define_method(:install) do
        bin.install "kairos"
      end
    end
  end

  test do
    system "#{bin}/kairos", "--help"
  end
end
