# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kairos < Formula
  desc "Git Context Engine — understands project history to generate high-quality commit messages, tags, and changelogs using LLMs"
  homepage "https://github.com/afeldman/kairos"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/afeldman/kairos/releases/download/v0.2.0/kairos_0.2.0_macOS_arm64.tar.gz"
      sha256 "9b63c1c03748ab0ca01cc70f2b6573572e2eab7216189dfd7d242e987b8f75ce"

      define_method(:install) do
        bin.install "kairos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/afeldman/kairos/releases/download/v0.2.0/kairos_0.2.0_Linux_x86_64.tar.gz"
      sha256 "48c136099c556b1b7163e041bb0199a1df82f8515ed3082070eaa7c749320c25"
      define_method(:install) do
        bin.install "kairos"
      end
    end
  end

  test do
    system "#{bin}/kairos", "--help"
  end
end
